add order item properties logic
plentymarkets/plugin-payment-payone pull request #22
Opened 2021-05-11 07:07 UTC by j-konopka

### Description of the feature/fix:

Add missing order item properties logic. For the old and new logic. 

### Requirements that must be fulfilled:
- [ ] New version in `plugin.json` updated
- [ ] Changelog entry added
- [ ] Plugin can be built (`build-set`)
- [ ] Tested by the author
- [ ] Tested by a second person

@plentymarkets/team-order-payment
____________________
New version must be uploaded from PID 31920.

Further information about the plugin can be found in the [Wiki](https://wiki.plentymarkets.com/display/OP/Payone).

2021-05-11 07:14 UTC, cmanciu-plenty approved these changes

2021-05-11 09:13 UTC, estafilarakis requested changes

2021-05-11 09:13 UTC, estafilarakis commented on meta/documents/changelog_de.md
> +- Bestellmerkmale können nun korrekt verarbeitet werden.
```suggestion
- Bestelleigenschaften können nun korrekt verarbeitet werden.
```

2021-05-11 09:13 UTC, estafilarakis commented on meta/documents/changelog_en.md
> +- Order item properties can now be processed correctly.
```suggestion
- Order item order properties can now be processed correctly.
```

2021-05-12 06:58 UTC, estafilarakis approved these changes

2021-05-22 04:43 UTC, merged