New Klarna Methods Payone
plentymarkets/plugin-payment-payone pull request #28
Opened 2021-12-17 10:57 UTC by cmanciu-plenty

### Description of the feature/fix:

### Requirements that must be fulfilled:
- [ ] New version in `plugin.json` updated
- [ ] Changelog entry added
- [X ] Plugin can be built (`build-set`)
- [X] Tested by the author
- [ ] Tested by a second person

[Kanbanize Card](LINK)

@plentymarkets/team-order-payment
____________________
New version must be uploaded from PID 31920.

Further information about the plugin can be found in the [Wiki](https://wiki.plentymarkets.com/display/OP/Payone).

2021-12-20 12:25 UTC, j-konopka requested changes
See comments.

The migration to create the payment methods in the database is missing.

2021-12-20 12:25 UTC, j-konopka commented on src/Models/Settings.php
> +        if (isset($data['PAYONE_PAYONE_AMAZON_PAY'])) {
Copy & Paste fail ;)

2021-12-20 12:25 UTC, j-konopka commented on src/Models/Settings.php
> +        if (isset($data['PAYONE_PAYONE_AMAZON_PAY'])) {
Copy & Paste fail ;)

2021-12-20 13:10 UTC, cmanciu-plenty commented
Added Migration Also

2021-12-20 14:46 UTC, j-konopka approved these changes

2021-12-21 05:37 UTC, MKanitz approved these changes

2021-12-27 08:44 UTC, merged